---

- name: "This is the first play in this PlayBook to install HTTPD on all the hosts"
  hosts: 10.65.122.70
  become: true
  tasks:
   - name: "start the httpd service"
     service:
        name: httpd
        state: stopped
   - name: "install httpd"
     yum:
       name: httpd
       state: absent
     
